# Change these first
owner: codeskraps # Your GitHub organization or username, where this repository lives
repo: upptime_codeskraps_status # The name of this repository

sites:
  - name: codeskraps.com
    url: https://codeskraps.com
  # Add more websites here as needed
  # - name: Another Site
  #   url: https://another-site.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.codeskraps.com
  # baseUrl: /upptime_codeskraps_status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Codeskraps Status
  introTitle: "**Codeskraps Status** is the uptime monitor and status page for Codeskraps services."
  introMessage: This page provides real-time status information for Codeskraps services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Codeskraps
      href: https://codeskraps.com
  theme: dark # Options: light, dark, night
  themeColor: "#1a1a1a" # Primary color for the theme
  favicon: https://repo.codeskraps.com/codeskraps/Blog/src/main/static/favicon.ico
  metaTags:
    - name: "description"
      content: "Codeskraps services status page - real-time monitoring"
    - name: "viewport"
      content: "width=device-width, initial-scale=1.0"
    - name: "theme-color"
      content: "#1a1a1a"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
